#!/usr/bin/env python3
import json
import hashlib
import os
import pathlib
import subprocess
import tempfile


ROOT = pathlib.Path(__file__).resolve().parents[1]
INPUT = ROOT / "docs/tiny-fleet-artifacts-20260912/split-audit/fixture-input"
WRAPPER = ROOT / "scripts/mesh-tiny-fleet"


def build(out):
    env = dict(os.environ, TINY_FLEET_DIR=str(out))
    subprocess.run([str(WRAPPER), "split-audit"], check=True, env=env, capture_output=True, text=True)
    report = out / "split-audit" / "fixture-report.json"
    return json.loads(report.read_text())


def main():
    with tempfile.TemporaryDirectory() as temp:
        a, b = pathlib.Path(temp) / "a", pathlib.Path(temp) / "b"
        first, second = build(a), build(b)
        assert (a / "split-audit/fixture-report.json").read_bytes() == (b / "split-audit/fixture-report.json").read_bytes()
        assert first == second
        assert first["schema"] == "tiny-fleet-split-audit/v1"
        assert first["clean_split"]["disjoint"] is True
        assert first["clean_split"]["overlaps"] == {"repository": [], "blob_sha256": [], "time": [], "prompt_family": []}
        assert all(case["detected"] for case in first["mutation_controls"].values())
        assert first["content_leakage_controls"]["exact-copy"]["detected"] is True
        assert first["content_leakage_controls"]["near-duplicate"]["detected"] is True
        near_similarity = first["content_leakage_controls"]["near-duplicate"]["token_jaccard"]
        assert 0.75 <= near_similarity < 1.0
        statuses = {row["path"]: row["status"] for row in first["fixture_files"]}
        assert statuses["generated/autogenerated.jsonl"] == "excluded-generated"
        assert statuses["malformed/invalid.jsonl"] == "excluded-malformed-jsonl"
        assert statuses["duplicate-records.jsonl"] == "excluded-duplicate-record-id"
        assert all(len(row["sha256"]) == 64 for row in first["fixture_files"])
        for row in first["fixture_files"]:
            assert hashlib.sha256((INPUT / row["path"]).read_bytes()).hexdigest() == row["sha256"]
        hash_rows = [line.split("\t") for line in (a / "split-audit/fixture-hashes.tsv").read_text().splitlines()]
        assert hash_rows[0] == ["path", "sha256", "status"]
        report_hash = hashlib.sha256((a / "split-audit/fixture-report.json").read_bytes()).hexdigest()
        assert ["fixture-report.json", report_hash, "report"] in hash_rows
    print("tinyfleet split audit: OK (deterministic hashes, four split axes, mutation/leakage controls)")


if __name__ == "__main__":
    main()
